steps:
  - name: 'gcr.io/paketo-buildpacks/build:base-cnb'
    entrypoint: '/lifecycle/creator'
    args:
      - '--buildpacks'
      - 'gcr.io/paketo-buildpacks/java'
      - '--builder'
      - 'gcr.io/paketo-buildpacks/builder:base'
    dir: '/workspace'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rh-test', '.']
images: ['gcr.io/$PROJECT_ID/rh-test']
