spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/request-handler
    username: request-handler
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  application:
    name: request-handler
#server:
#  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

