spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: request-handler
          uri: lb://request-handler
          predicates:
            - Path=/test/**
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}